<?xml version="1.0" encoding="UTF-8"?>
<!--Lo que está entre paréntesis de forma_geometrica debe ir en "," ya que son los campos que van a existir-->
<!--ELEMENT forma_geometrica (nombre | caracteristicas | numero_de_lados)-->
<!--Falta también un elemento que es el de caracteristicas con sus subelementos correspondientes-->

<!DOCTYPE forma_geometrica [
        <!ELEMENT forma_geometrica (nombre, caracteristicas, numero_de_lados)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT caracteristicas (color, tipo)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT tipo (#PCDATA)>
        <!ELEMENT numero_de_lados (#PCDATA)>
]>

<forma_geometrica>
    <nombre>rombo</nombre>
    <caracteristicas>
        <color>naranja</color>
        <tipo>plana</tipo>
    </caracteristicas>
    <numero_de_lados>4</numero_de_lados>
</forma_geometrica>
